# Generated by Django 3.2.18 on 2023-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Abonelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Ayarları',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slide_Gösterisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='image')),
                ('slide_title', models.CharField(max_length=150)),
                ('slide_descrp', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ürün_Listesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ürün_image_name', models.ImageField(upload_to='image')),
                ('ürün_descrption', models.CharField(max_length=50)),
                ('ürün_price', models.CharField(max_length=50)),
            ],
        ),
    ]
