# Generated by Django 3.2.18 on 2023-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide_gösterisi',
            name='slide_image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='ürün_listesi',
            name='ürün_image_name',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
