# Generated by Django 3.2.18 on 2023-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230518_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='İletişim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('ad', models.CharField(max_length=50)),
                ('istek', models.TextField()),
            ],
        ),
    ]
