# Generated by Django 3.2.18 on 2023-05-24 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230524_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='kkb_hesabim',
            name='essisid',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
