# Generated by Django 3.2.18 on 2023-05-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_kkb_hesabim_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkb_hesabim',
            name='profil_photo',
            field=models.ImageField(default='image/user.png', upload_to='image/'),
        ),
    ]
