# Generated by Django 3.2.18 on 2023-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_kkb_hesabim_profil_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kkb_hesabim',
            name='essisid',
        ),
        migrations.AlterField(
            model_name='kkb_hesabim',
            name='profil_photo',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
