# Generated by Django 3.2.18 on 2023-05-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_total_fiyat_sepetim_total_atted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepetOnay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepet_total_fiyati', models.IntegerField()),
                ('sepet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sepetim')),
            ],
        ),
    ]
