# Generated by Django 3.2.18 on 2023-05-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_sepetonay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepetim',
            name='total_atted',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sepetim',
            name='ürün_fiyat',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sepetonay',
            name='sepet_total_fiyati',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
