# Generated by Django 3.2.18 on 2023-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_sepetim_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepetim',
            name='ürün_fiyat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
