# Generated by Django 3.2.18 on 2023-06-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_sepetim_ürün_fiyat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SepetOnay',
        ),
    ]
