# Generated by Django 3.2.18 on 2023-06-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delete_sepetonay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ürün_listesi',
            name='slug_ürün',
            field=models.SlugField(default=''),
        ),
    ]
