# Generated by Django 3.2.18 on 2023-06-02 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_ürün_listesi_slug_ürün'),
    ]

    operations = [
        migrations.AddField(
            model_name='ürün_listesi',
            name='page_search',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
